# Change these first
owner: Aissi17 # Your GitHub organization or username, where this repository lives
repo: upptime-fentech # The name of this repository

sites:
  - name: Fentech Carrefour
    url: https://carrefour.prod.clairvoyant.fentech.ai
    icon : https://carrefour.prod.clairvoyant.fentech.ai/img/logo.svg

status-website: # Status website (optional)
  baseUrl: /upptime-fentech
  name: https://clairvoyant-carreofur.github.io/upptime-fentech/

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/60 * * * *"
